pythonProject1/blueprints/front_page.py
from flask import Blueprint, render_template

bp = Blueprint("front_page", __name__, url_prefix="/")



@bp.route("/")
def fpage():
    return render_template("FrontPage.html")

pythonProject1/blueprints/post.py
from flask import Blueprint, render_template, request, g, redirect, url_for, current_app
from .forms import BlogForm, CommentForm
from models import BlogModel, CommentModel
from exts import db
from decorators import login_required

bp = Blueprint("post", __name__, url_prefix='/post')

"""@bp.route('/')
def index():
    page = request.args.get('page', default=1, type=int)
    start = (page - 1) * current_app.config.get('PER_PAGE_COUNT')
    end = start + current_app.config.get('PER_PAGE_COUNT')
    query_obj = BlogModel.query.order_by(BlogModel.create_time.desc())
    total = query_obj.count()
    posts = query_obj.slice(start, end)
    pagination = Pagination(bs_version=4, page=page, total=total, outer_widows=0, inner_widows=2, alignment="center")
    context = {
        "posts": posts,
        "pagination": pagination
    }
    return render_template("index.html", **context)"""


@bp.route('/')
def index():
    if not g.user:
        return redirect(url_for('user.login'))
    blogs = BlogModel.query.order_by(BlogModel.create_time.desc()).all()
    return render_template("index.html", blogs=blogs)

#@bp.route('/bc/public', methods=['GET', 'POST'])
#@login_required
#def public_bc():
#    if request.method == 'GET':
#        return render_template("public_blog.html")
#    else:
#        form = BlogForm(request.form)
#        if form.validate():
#            title = form.title.data
#            content = form.content.data
#            blog = BlogModel(title=title, content=content, author=g.user)
#            db.session.add(blog)
#            db.session.commit()
#            return redirect("/")
        #todo：跳转到本片问答详情页面
#        else:
#            print(form.errors)
#            return redirect(url_for('post.public_bc'))


@bp.route('/bc/public', methods=['GET', 'POST'])
def public_blog():
    if not g.user:
        return redirect(url_for('user.login'))
    if request.method == 'GET':
        return render_template("public_blog.html")
    else:
        form = BlogForm(request.form)
        if form.validate():
            title = form.title.data
            content = form.content.data
            blog = BlogModel(title=title, content=content, author=g.user)
            db.session.add(blog)
            db.session.commit()
            return redirect("/post")
        else:
            print(form.errors)
            return redirect(url_for('post.public_blog'))


@bp.route("/bc/detail/<bc_id>")
def bc_detail(bc_id):
    blog = BlogModel.query.get(bc_id)
    return render_template("detail.html", blog=blog)


#@bp.post("/comment/public")
#@login_required
#def public_comment(model_id=None):
#    form = CommentForm(request.form)
#    if form.validate():
#        content = form.content.data
#        blog_id = form.blog_id.data
#        comment = CommentModel(content=content, blog_id=blog_id, author_id=g.user.id)
#        db.session.add(comment)
#        db.session.commit()
#        return redirect(url_for('post.bc_detail', bc_id=blog_id))
#    else:
#        print(form.errors)
#        return redirect(url_for('post.bc_detail', bc_id=request.form.get("blog_id")))


@bp.post("/comment/public")
def public_comment(model_id=None):
    if not g.user:
        return redirect(url_for('user.login'))
    form = CommentForm(request.form)
    if form.validate():
        content = form.content.data
        blog_id = form.blog_id.data
        comment = CommentModel(content=content, blog_id=blog_id, author_id=g.user.id)
        db.session.add(comment)
        db.session.commit()
        return redirect(url_for('post.bc_detail', bc_id=blog_id))
    else:
        print(form.errors)
        return redirect(url_for('post.bc_detail', bc_id=request.form.get("blog_id")))


@bp.route("/search")
def search():
    q = request.args.get("q")
    blogs = BlogModel.query.filter(BlogModel.title.contains(q)).all()
    return render_template("index.html", blogs=blogs)

pythonProject1/blueprints/user.py
import random
from flask import Blueprint, render_template, request, jsonify, redirect, url_for, session, flash, abort
from flask_wtf import form
from sqlalchemy.sql.functions import current_user
from sqlalchemy.testing.pickleable import User
from werkzeug.security import generate_password_hash, check_password_hash
from decorators import login_required
from exts import mail, db
from flask_mail import Message
import string
from models import EmailCaptchaModel, UserModel, BlogModel
from .forms import RegisterForm, LoginForm, EditProfileForm, ChangeForm

__package__ = 'blueprints'

bp = Blueprint("user", __name__, url_prefix="/user")


@bp.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "GET":
        return render_template("login1.html")
    else:
        form = LoginForm(request.form)
        # 检查格式
        if form.validate():
            email = form.email.data
            password = form.password.data
            user = UserModel.query.filter_by(email=email).first()
            # 检查是否存在该用户
            if not user:
                flash("用户未找到")
                return redirect(url_for("user.login"))
            # 检查密码
            if check_password_hash(user.password, password):
                 session["user_id"] = user.id
                 return redirect(url_for("front_page.fpage"))
            else:
                flash("密码错误")
                return redirect(url_for("user.login"))
        else:
            flash("表单错误：" + str(form.errors))
            return redirect(url_for("user.login"))


# GET:从服务器上获取数据
# POST：将客户端的数据提交给服务器
@bp.route("/register", methods=["GET", "POST"])
def register():
    if request.method == "GET":
        return render_template("register4.html")
    else:
        # 验证用户提交的邮箱和验证码是否对应且正确
        # 表单验证：flask-wtf
        form = RegisterForm(request.form)
        # 验证成功，创建用户
        if form.validate():
            email = form.email.data
            username = form.username.data
            password = form.password.data
            user = UserModel(username=username, email=email, password=generate_password_hash(password))
            db.session.add(user)
            db.session.commit()
            return redirect(url_for("user.login"))
        # 注册失败
        else:
            print(form.errors)
            return redirect(url_for("user.register"))


@bp.route("/captcha/email", methods=["GET"])
def get_email_captcha():
    try:
        email = request.args.get("email") #获取注册用户邮箱
        #生成验证码
        source = string.digits*4
        captcha = random.sample(source, 4)
        captcha = "".join(captcha)
        #发送验证码给注册用户
        message = Message(subject="您的注册码", recipients=[email], body=f"您的验证码是{captcha}")
        mail.send(message)
        print(captcha)
        #将验证码存入数据库
        email_captcha = EmailCaptchaModel(email=email, captcha=captcha)
        db.session.add(email_captcha)
        db.session.commit()
        return jsonify({"code": 200, "message": "验证码已发送", "data": None})
    except Exception as e:
        return jsonify({"code": 500, "message": str(e), "data": None})


@bp.route("/logout")
def logout():
    session.clear()
    return redirect("/")


@bp.route("/view/<username>")
def view(username):
    user = UserModel.query.filter_by(username=username).first()
    if user is None:
        abort(404)
    posts = user.posts.order_by(BlogModel.create_time.desc()).all()
    return render_template('user.html', user=user)


# 用户级别的资料编辑器
@bp.route("/edit/<username>", methods=["GET", "POST"])
@login_required
def edit_profile():
    form = EditProfileForm()
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.location = form.location.data
        current_user.about_me = form.about_me.data
        db.session.add(current_user)
        flash("您的资料已修改")
        return redirect(url_for("user.view"))
    form.name.data = current_user.username
    form.location.data = current_user.location
    form.about.me = current_user.about_me
    return render_template("edit_profile.html", form=form)


@bp.route("/change_password", methods=["GET", "POST"])
def change_password():
    if request.method == "GET":
        return render_template("change_password.html")
    else:
        form = ChangeForm(request.form)
        if form.validate():
            user = UserModel.query.filter_by(email=form.email.data).first()
            password = form.password.data
            user.password = generate_password_hash(password)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for("user.login"))
        else:
            print(form.errors)
            return redirect(url_for("user.change_password"))

pythonProject1/templates/base.html
<!DOCTYPE html>
<html lang="ch">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{{  url_for('static',filename='bootstrap/bootstrap.4.6.min.css')}}">
    <link rel="stylesheet" href="{{  url_for('static',filename='css/init.css')}}">
    {% block head %} {% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="#">食堂评价系统</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="/">首页 <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('post.public_blog') }}">发布博客</a>
                    </li>
                    <li class="nav-item ml-2">
                        <form class="form-inline my-2 my-lg-0" method="GET" action="{{url_for('post.search')}}">
                            <input class="form-control mr-sm-2" type="search" placeholder="关键字" aria-label="Search" name="q">
                            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">搜索</button>
                        </form>
                    </li>
                </ul>
                <ul class="navbar-nav">
                    {% if user %}
                        <li class="nav-item">
                        <sqan class="nav-link" >{{user.username}}</sqan>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('user.logout') }}">退出登录</a>
                    {% else %}
                          <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('user.login') }}">登录</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('user.register') }}">注册</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>


        {% block body %}{% endblock %}
</body>

</html>

pythonProject1/templates/index.html
{% block head %}
<meta charset="utf-8">
<style>
    .nav{
        width: 100%;
        height: 60px;
        background-color: #006600;
        margin-left: 0;
        display: block;
        margin-bottom: 0;
    }
    a{
        text-decoration: none;
    }
    .nav ul li{
        float: left;
        list-style-type: none;
        padding: 0 50px ;
        line-height: 60px;

    }
    .nav>ul>li>a {
        color:lightgray;
        font-size: 20px;
    }

    .学部食堂{
        position: absolute;
        padding-left: 0;
        margin-top:0;
        height:60px;
        width: 100%;
        left:0;
        background-color: rgb(249,249,248);
        border-left: 1px solid black;
        border-right: 1px solid black;
        border-bottom: 1px solid gray;
        overflow: hidden;
        clear: both;
        display: none;
    }
    .学部食堂 ul{
        position: absolute;
        left:0;

        overflow: hidden;
        clear: both;
        z-index: 200;
    }
    .学部食堂 ul li{
        list-style-type: none;
        float: left;
        margin-left: 0;

    }
    .学部食堂 ul li a{
        color: black;
        font-size: 15px;
        padding-left: 100px;

    }
    .食堂概况:hover>.学部食堂{
        display: block;
        z-index: 200;
    }
    .食堂概况:hover>.学部食堂>ul>li>a:hover{
        color: darkgreen;
    }
    .nav>ul>li>a:hover{
        color: white;
    }
    .用户{
        position: absolute;
        right:10px;

    }
        .row .col-10{
            position: relative;
            top:50px;
            margin: 20px 40px;
            border: #0c5460;
            width:90%;
            height:500px;
            border-radius: 40px;

        }
        .side-blog img{
            width:60px;
            height:60px;
        }
        .btn-primary{
            width:80px;
            height:40px;
            background-color: #b4ac4d;
            border-radius:20px;
            position: relative;
            top:-50px;
        }
        .form-control{
            height:40px;
            width:600px;
            border-radius: 15px;


        }
        .comment-group li{
            border-radius: 15px;
            width:90%;
            height:100px;
            background: white;
        }
        .blog-content{
            border-radius: 15px;
            width:90%;
            height:300px;
            background: white;
            font-family: "Microsoft YaHei UI" , "system-ui";
            font-weight: lighter;
        }
        .blog-title{
            font-size: large;
            font-weight: bold;
            font-family: "Arial", sans-serif;
        }
        .nav-item1{
            position: absolute;
            right:280px;
            font-size: 20px;
            font-weight:700;
            font-family:"Microsoft JhengHei";
            width:100px;
            display:block;
        }
        .nav-link3{
            position: absolute;
            right:200px;
            font-size: 2px;
            font-weight:700;
            font-family:"Microsoft JhengHei";
            width:80px;
            display:block;
        }
        .nav-link1{
            position: absolute;
            right:280px;
            font-size: 20px;
            font-weight:700;
            font-family:"Microsoft JhengHei";
            width:100px;
            display:block;
        }
        .nav-link2{
            position: absolute;
            right:200px;
            font-size: 2px;
            font-weight:700;
            font-family:"Microsoft JhengHei";
            width:80px;
            display:block;
        }
        .add_content{
            position:fixed;
            right:30px;
            top:700px;
            width:80px;
            height:80px;
            display: block;
        }
    .blog-ul {
        list-style: none;
        padding: 0;
    }

    .blog-ul li {
        border-bottom: 1px solid #ddd; /* 添加分隔线 */
        padding: 20px 0;
        display: flex;
        align-items: center;
    }

    .blog-avatar {
    margin-right: 20px;
}

    .side-blog-avatar {
        border-radius: 50%; /* 使头像为圆形 */
        width: 60px; /* 头像宽度 */
        height: 60px; /* 头像高度 */
    }

    .blog-item {
    display: flex;
    align-items: flex-start; /* 使头像和标题在顶部对齐 */
    border-bottom: 1px solid #ddd; /* 添加分隔线 */
    padding: 20px 0;
    height: 150px; /* 降低帖子高度 */
    background: rgba(240, 240, 240, 0.5); /* 添加灰色半透明背景 */
}

    .blog-title {
        color: #333; /* 设置标题颜色 */
        font-size: 1.5em; /* 增加标题字体大小 */
        margin-bottom: 10px;
}

    .blog-title a {
    color: inherit; /* 保持链接颜色与标题一致 */
    text-decoration: none; /* 去除下划线 */
}

    .blog-title a:hover {
    color: #007bff; /* 鼠标悬停时改变颜色 */
    text-decoration: underline; /* 鼠标悬停时添加下划线 */
}

    .blog-content {
    flex: 1;
}

    .blog-detail {
    font-size: 0.9em;
    color: #999; /* 设置详细信息颜色 */
}

    .blog-author {
    margin-right: 20px;
}

    .write_button {
    text-align: center;
    margin-top: 20px;
}

    .blog-text {
        color: #666; /* 设置内容颜色 */
        font-size: 1em;
        margin-bottom: 10px;
        overflow: hidden; /* 防止内容溢出 */
        text-overflow: ellipsis; /* 显示省略号 */
        display: -webkit-box;
        -webkit-line-clamp: 3; /* 限制显示行数 */
        -webkit-box-orient: vertical;
    }
</style>
{% endblock %}

{% block body %}
<div class = "nav">
    <ul>
        <li class = "食堂概况">   <!-- 这里看每个学部的食堂-->
            <a href="#">食堂概况</a>
            <div class="学部食堂">
                <ul >
                    <li><a href="#">工学部食堂</a></li>
                    <li><a href="#">文理学部食堂</a></li>
                    <li><a href="#">信息学部食堂</a></li>
                    <li><a href="#">医学部食堂</a></li>
                </ul>
            </div>
        </li>
        <li class = "发现">   <!-- 这里是发帖子，看帖子区-->
            <a href="/post">发现</a>
        </li >

        <li class = "我的">
            {% if user %}
            <a href="{{ url_for('user.view', username=user.username) }}"> 我的</a>
            {% endif %}
        </li>
        <li class = "用户" >
            <a href="/"><img src="../static/images/标志.png" alt = "user" height = 60px ></a>
        </li>
    </ul>
    <ul class="navbar-nav">
        {% if user %}
        <li class="nav-item1">
            <sqan class="nav-link" >{{user.username}}</sqan>
        </li>
        <li class="nav-item">
            <a class="nav-link3" href="{{ url_for('user.logout') }}">退出登录</a>
            {% else %}
        <li class="nav-item">
            <a class="nav-link1" href="{{ url_for('user.login') }}">登录</a>
        </li>
        <li class="nav-item2">
            <a class="nav-link2" href="{{ url_for('user.register') }}">注册</a>
        </li>
        {% endif %}
    </ul>
</div>
 <div class="row" style="margin-top: 20px;">
            <div class="col"></div>
            <div class="col-10">
                <ul class="blog-ul">
                    {% for blog in blogs %}
                    <li class="blog-item">
                        <div class="blog-content">
                            <div class="blog-avatar">
                            <a href="{{ url_for('user.view', username=blog.author.username) }}"><img class="side-blog-avatar" src="../static/images/avatar.jpg" alt=""></a>
                        </div>
                            <div class="blog-title"><a href="{{url_for('post.bc_detail',bc_id=blog.id)}}">{{blog.title}}</a></div>
                            <div class="blog-text">{{ blog.content }}</div>
                            <div class="blog-detail">
                                <span class="blog-author">{{ blog.author.username }}</span>
                                <span class="blog-time">{{ blog.create_time }}</span>
                            </div>
                        </div>
                    </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="col"></div>
        </div>
    <div class="write_button">
        <a class="add_content" href="/post/bc/public"><img class="add_content" alt="按钮" src="../static/images/发帖标志.png"></a>
    </div>
{% endblock %}

pythonProject1/templates/index2.html
{% block head %}
<meta charset="utf-8">
<style>
    .nav{
        width: 100%;
        height: 60px;
        background-color: #006600;
        margin-left: 0;
        display: block;
        margin-bottom: 0;
    }
    a{
        text-decoration: none;
    }
    .nav ul li{
        float: left;
        list-style-type: none;
        padding: 0 50px ;
        line-height: 60px;

    }
    .nav>ul>li>a {
        color:lightgray;
        font-size: 20px;
    }

    .学部食堂{
        position: absolute;
        padding-left: 0;
        margin-top:0;
        height:60px;
        width: 100%;
        left:0;
        background-color: rgb(249,249,248);
        border-left: 1px solid black;
        border-right: 1px solid black;
        border-bottom: 1px solid gray;
        overflow: hidden;
        clear: both;
        display: none;
    }
    .学部食堂 ul{
        position: absolute;
        left:0;

        overflow: hidden;
        clear: both;
        z-index: 200;
    }
    .学部食堂 ul li{
        list-style-type: none;
        float: left;
        margin-left: 0;

    }
    .学部食堂 ul li a{
        color: black;
        font-size: 15px;
        padding-left: 100px;

    }
    .食堂概况:hover>.学部食堂{
        display: block;
        z-index: 200;
    }
    .食堂概况:hover>.学部食堂>ul>li>a:hover{
        color: darkgreen;
    }
    .nav>ul>li>a:hover{
        color: white;
    }
    .用户{
        position: absolute;
        right:10px;

    }
        .row .col-10{
            position: relative;
            top:50px;
            margin: 20px 40px;
            border: #0c5460;
            width:90%;
            height:500px;
            border-radius: 40px;

        }
        .side-blog img{
            width:60px;
            height:60px;
        }
        .btn-primary{
            width:80px;
            height:40px;
            background-color: #b4ac4d;
            border-radius:20px;
            position: relative;
            top:-50px;
        }
        .form-control{
            height:40px;
            width:600px;
            border-radius: 15px;


        }
        .comment-group li{
            border-radius: 15px;
            width:90%;
            height:100px;
            background: white;
        }
        .blog-content{
            border-radius: 15px;
            width:90%;
            height:300px;
            background: white;
            font-family: "Microsoft YaHei UI" , "system-ui";
            font-weight: lighter;
        }
        .blog-title{
            font-size: large;
            font-weight: bold;
            font-family: "Arial", sans-serif;
        }
        .nav-item1{
            position: absolute;
            right:280px;
            font-size: 20px;
            font-weight:700;
            font-family:"Microsoft JhengHei";
            width:100px;
            display:block;
        }
        .nav-link3{
            position: absolute;
            right:200px;
            font-size: 2px;
            font-weight:700;
            font-family:"Microsoft JhengHei";
            width:80px;
            display:block;
        }
</style>
{% endblock %}

{% block body %}
<div class = "nav">
    <ul>
        <li class = "食堂概况">   <!-- 这里看每个学部的食堂-->
            <a href="#">食堂概况</a>
            <div class="学部食堂">
                <ul >
                    <li><a href="#">工学部食堂</a></li>
                    <li><a href="#">文理学部食堂</a></li>
                    <li><a href="#">信息学部食堂</a></li>
                    <li><a href="#">医学部食堂</a></li>
                </ul>
            </div>
        </li>
        <li class = "发现">   <!-- 这里是发帖子，看帖子区-->
            <a href="/post">发现</a>
        </li >

        <li class = "我的">
            {% if user %}
            <a href="{{ url_for('user.view', username=user.username) }}"> 我的</a>
            {% endif %}
        </li>
        <li class = "用户" >
            <a href="/"><img src="../static/images/标志.png" alt = "user" height = 60px ></a>
        </li>
    </ul>
    <ul class="navbar-nav">
        {% if user %}
        <li class="nav-item1">
            <sqan class="nav-link" >{{user.username}}</sqan>
        </li>
        <li class="nav-item">
            <a class="nav-link3" href="{{ url_for('user.logout') }}">退出登录</a>
            {% else %}
        <li class="nav-item">
            <a class="nav-link1" href="{{ url_for('user.login') }}">登录</a>
        </li>
        <li class="nav-item2">
            <a class="nav-link2" href="{{ url_for('user.register') }}">注册</a>
        </li>
        {% endif %}
    </ul>
</div>
        <div class="row">
            <div class="col"></div>
            <div class="col-10">
                <ul class="blog-ul">
                    {% for blog in blogs %}
                    <li>
                        <div class="side-blog">
                            <img class="side-blog-avatar" src="../static/images/空白用户.jpg" alt="">
                        </div>
                        <div class="blog-main">
                            <div class="blog-title"><a href="{{url_for('post.bc_detail',bc_id=blog.id)}}">{{blog.title}}</a></div>
                            <div class="blog-content">{{ blog.content }}</div>
                            <div class="blog-detail">
                                <span class="blog-author">{{ blog.author.username }}</span>
                                <span class="blog-time">{{ blog.create_time }}</span>
                            </div>
                        </div>
                    </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="col"></div>
        </div>
{% endblock %}

pythonProject1/templates/user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>用户个人信息</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f0f0f0;
        }
        .page-header {
            max-width: 300px;
            margin: 20px auto;
            padding: 20px;
            background-color: rgba(255, 255, 255, 0.8);
            box-shadow: 0px 0px 10px rgba(0,0,0,0.1);
            border-radius: 10px;
            text-align: center;
        }
        h1 {
            color: #333;
        }
        p {
            margin-bottom: 15px;
        }
        a {
            color: #006400;
        }
        .post {
            margin: 20px auto;
            padding: 20px;
            background-color: rgba(255, 255, 255, 0.8);
            box-shadow: 0px 0px 10px rgba(0,0,0,0.1);
            border-radius: 10px;
            max-width: 300px;
        }
        .nav{
            width: 100%;
            height: 60px;
            background-color: #006600;
            margin-left: 0;
            display: block;
            margin-bottom: 0;
        }
        a{
            text-decoration: none;
        }
        .nav ul li{
            float: left;
            list-style-type: none;
            padding: 0 50px ;
            line-height: 60px;

        }
        .nav>ul>li>a {
            color:lightgray;
            font-size: 20px;
        }

        .学部食堂{
            position: absolute;
            padding-left: 0;
            margin-top:0;
            height:60px;
            width: 100%;
            left:0;
            background-color: rgb(249,249,248);
            border-left: 1px solid black;
            border-right: 1px solid black;
            border-bottom: 1px solid gray;
            overflow: hidden;
            clear: both;
            display: none;
        }
        .学部食堂 ul{
            position: absolute;
            left:0;

            overflow: hidden;
            clear: both;
            z-index: 200;
        }
        .学部食堂 ul li{
            list-style-type: none;
            float: left;
            margin-left: 0;

        }
        .学部食堂 ul li a{
            color: black;
            font-size: 15px;
            padding-left: 100px;

        }
        .食堂概况:hover>.学部食堂{
            display: block;
            z-index: 200;
        }
        .食堂概况:hover>.学部食堂>ul>li>a:hover{
            color: darkgreen;
        }
        .nav>ul>li>a:hover{
            color: white;
        }
        .用户{
            position: absolute;
            right:10px;

        }
        .nav-item1{
            position: absolute;
            right:280px;
            font-size: 20px;
            font-weight:700;
            font-family:"Microsoft JhengHei";
            width:100px;
            display:block;
        }
        .nav-link3{
            position: absolute;
            right:200px;
            font-size: 2px;
            font-weight:700;
            font-family:"Microsoft JhengHei";
            width:80px;
            display:block;
        }
    </style>
</head>
<body>
<div class = "nav">
    <ul>
        <li class = "食堂概况">   <!-- 这里看每个学部的食堂-->
            <a href="#">食堂概况</a>
            <div class="学部食堂">
                <ul >
                    <li><a href="#">工学部食堂</a></li>
                    <li><a href="#">文理学部食堂</a></li>
                    <li><a href="#">信息学部食堂</a></li>
                    <li><a href="#">医学部食堂</a></li>
                </ul>
            </div>
        </li>
        <li class = "发现">   <!-- 这里是发帖子，看帖子区-->
            <a href="/post">发现</a>
        </li >

        <li class = "我的">
            {% if user %}
            <a href="{{ url_for('user.view', username=user.username) }}"> 我的</a>
            {% endif %}
        </li>
        <li class = "用户" >
            <a href="/"><img src="../static/images/标志.png" alt = "user" height = 60px ></a>
        </li>
    </ul>
    <ul class="navbar-nav">
        {% if user %}
        <li class="nav-item1">
            <sqan class="nav-link" >{{user.username}}</sqan>
        </li>
        <li class="nav-item">
            <a class="nav-link3" href="{{ url_for('user.logout') }}">退出登录</a>
            {% else %}
        <li class="nav-item">
            <a class="nav-link1" href="{{ url_for('user.login') }}">登录</a>
        </li>
        <li class="nav-item2">
            <a class="nav-link2" href="{{ url_for('user.register') }}">注册</a>
        </li>
        {% endif %}
    </ul>
</div>
    {% block page_content %}
    <div class="page-header">
        <h1>{{ user.username }}</h1>
        <p>Email: {{ user.email }}</p>
        {% if user.name or user.location %}
        <p>
            {% if user.name %}Name: {{ user.name }}{% endif %}
        </p>
        {% endif %}
        <p><a href="mailto:{{ user.email }}"></a></p>
        {% if user.about_me %}
        <p>
            About me: {{ user.about_me }}
        </p>
        {% endif %}
        <p>
            Member since: {{user.join_time}}.
        </p>
    </div>

    <!-- 用户发的贴子 -->
    {% for post in user.posts %}
    <div class="post">
        <h2><a href="{{url_for('post.bc_detail',bc_id=post.id)}}">{{ post.title }}</a></h2>
        <p>{{ post.content }}</p>
        <p>Posted on: {{ post.create_time}}</p>
    </div>
    {% endfor %}

    {% endblock %}
</body>
</html>